"""add_inventory_transaction_model

Revision ID: 307fd2c32f88
Revises: 42248758367c
Create Date: 2026-06-20 21:00:39.249252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307fd2c32f88'
down_revision: Union[str, Sequence[str], None] = '42248758367c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_inventory_transactions_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_inventory_transactions_voucher_id_vouchers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index(op.f('ix_inventory_transactions_stock_item_id'), 'inventory_transactions', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_voucher_id'), 'inventory_transactions', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_voucher_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_stock_item_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
