"""add_voucher_models

Revision ID: 42248758367c
Revises: 856fcf11cfb1
Create Date: 2026-06-20 20:56:12.125296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42248758367c'
down_revision: Union[str, Sequence[str], None] = '856fcf11cfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher_sequences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('voucher_type', sa.Enum('SALES', 'PURCHASE', 'PAYMENT', 'RECEIPT', 'CONTRA', 'JOURNAL', 'OPENING', name='vouchertype'), nullable=False),
    sa.Column('last_serial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_voucher_sequences_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_voucher_sequences_financial_year_id_financial_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'financial_year_id', 'voucher_type', name=op.f('pk_voucher_sequences'))
    )
    op.create_table('vouchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('voucher_type', sa.Enum('SALES', 'PURCHASE', 'PAYMENT', 'RECEIPT', 'CONTRA', 'JOURNAL', 'OPENING', name='vouchertype'), nullable=False),
    sa.Column('voucher_number', sa.String(length=100), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='voucherstatus'), nullable=False),
    sa.Column('narration', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vouchers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_vouchers_financial_year_id_financial_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouchers')),
    sa.UniqueConstraint('company_id', 'financial_year_id', 'voucher_type', 'voucher_number', name='uq_voucher_number')
    )
    op.create_index(op.f('ix_vouchers_company_id'), 'vouchers', ['company_id'], unique=False)
    op.create_index(op.f('ix_vouchers_financial_year_id'), 'vouchers', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_number'), 'vouchers', ['voucher_number'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_type'), 'vouchers', ['voucher_type'], unique=False)
    op.create_table('voucher_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_voucher_entries_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_voucher_entries_voucher_id_vouchers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_entries'))
    )
    op.create_index(op.f('ix_voucher_entries_ledger_id'), 'voucher_entries', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_voucher_entries_voucher_id'), 'voucher_entries', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_entries_voucher_id'), table_name='voucher_entries')
    op.drop_index(op.f('ix_voucher_entries_ledger_id'), table_name='voucher_entries')
    op.drop_table('voucher_entries')
    op.drop_index(op.f('ix_vouchers_voucher_type'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_voucher_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_financial_year_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('voucher_sequences')
    # ### end Alembic commands ###
