"""add_banking_models_and_ledger_type

Revision ID: 666e6cfbd62b
Revises: 6ded4c4acc82
Create Date: 2026-06-22 00:37:15.238624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666e6cfbd62b'
down_revision: Union[str, Sequence[str], None] = '6ded4c4acc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type manually
    sa.Enum('GENERAL', 'CASH', 'BANK', name='ledgertype').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bank_accounts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_bank_accounts_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('ledger_id', name=op.f('uq_bank_accounts_ledger_id'))
    )
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_accounts_company_id'), 'bank_accounts', ['company_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_ledger_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_ledger_id'], ['ledgers.id'], name=op.f('fk_bank_statements_bank_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bank_statements_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statements'))
    )
    op.create_index(op.f('ix_bank_statements_bank_ledger_id'), 'bank_statements', ['bank_ledger_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_company_id'), 'bank_statements', ['company_id'], unique=False)
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], name=op.f('fk_bank_statement_lines_statement_id_bank_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_bank_statement_lines_voucher_id_vouchers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statement_lines'))
    )
    op.create_index(op.f('ix_bank_statement_lines_statement_id'), 'bank_statement_lines', ['statement_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_payment_allocations_voucher_id_vouchers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_voucher_id'), 'payment_allocations', ['voucher_id'], unique=False)

    # Add column as nullable first
    op.add_column('ledgers', sa.Column('ledger_type', sa.Enum('GENERAL', 'CASH', 'BANK', name='ledgertype'), nullable=True))

    # Update existing rows
    op.execute("UPDATE ledgers SET ledger_type = 'GENERAL'")

    # Make it non-nullable
    op.alter_column('ledgers', 'ledger_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledgers', 'ledger_type')
    op.drop_index(op.f('ix_payment_allocations_voucher_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_bank_statement_lines_statement_id'), table_name='bank_statement_lines')
    op.drop_table('bank_statement_lines')
    op.drop_index(op.f('ix_bank_statements_company_id'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_bank_ledger_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_bank_accounts_company_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
