"""add_fy_closing_models

Revision ID: 6ded4c4acc82
Revises: 856951d24c7b
Create Date: 2026-06-22 00:23:38.705598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6ded4c4acc82'
down_revision: Union[str, Sequence[str], None] = '856951d24c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fy_opening_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_type', postgresql.ENUM('DEBIT', 'CREDIT', name='balancetype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_fy_opening_balances_financial_year_id_financial_years'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_fy_opening_balances_ledger_id_ledgers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fy_opening_balances'))
    )
    op.create_index(op.f('ix_fy_opening_balances_financial_year_id'), 'fy_opening_balances', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_fy_opening_balances_ledger_id'), 'fy_opening_balances', ['ledger_id'], unique=False)
    op.create_table('fy_stock_openings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_fy_stock_openings_financial_year_id_financial_years'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_fy_stock_openings_stock_item_id_stock_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_fy_stock_openings_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fy_stock_openings'))
    )
    op.create_index(op.f('ix_fy_stock_openings_financial_year_id'), 'fy_stock_openings', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_fy_stock_openings_stock_item_id'), 'fy_stock_openings', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_fy_stock_openings_warehouse_id'), 'fy_stock_openings', ['warehouse_id'], unique=False)
    op.add_column('financial_years', sa.Column('previous_fy_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_financial_years_previous_fy_id_financial_years'), 'financial_years', 'financial_years', ['previous_fy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_financial_years_previous_fy_id_financial_years'), 'financial_years', type_='foreignkey')
    op.drop_column('financial_years', 'previous_fy_id')
    op.drop_index(op.f('ix_fy_stock_openings_warehouse_id'), table_name='fy_stock_openings')
    op.drop_index(op.f('ix_fy_stock_openings_stock_item_id'), table_name='fy_stock_openings')
    op.drop_index(op.f('ix_fy_stock_openings_financial_year_id'), table_name='fy_stock_openings')
    op.drop_table('fy_stock_openings')
    op.drop_index(op.f('ix_fy_opening_balances_ledger_id'), table_name='fy_opening_balances')
    op.drop_index(op.f('ix_fy_opening_balances_financial_year_id'), table_name='fy_opening_balances')
    op.drop_table('fy_opening_balances')
    # ### end Alembic commands ###
