"""add_inventory_masters_models

Revision ID: 7057ba6e0177
Revises: fe30ead5ce1d
Create Date: 2026-06-20 20:46:35.286170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7057ba6e0177'
down_revision: Union[str, Sequence[str], None] = 'fe30ead5ce1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_groups_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['stock_groups.id'], name=op.f('fk_stock_groups_parent_id_stock_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_groups'))
    )
    op.create_index(op.f('ix_stock_groups_company_id'), 'stock_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_groups_name'), 'stock_groups', ['name'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('stock_group_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.Enum('PRODUCT', 'SERVICE', name='itemtype'), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_items_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_group_id'], ['stock_groups.id'], name=op.f('fk_stock_items_stock_group_id_stock_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_stock_items_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items'))
    )
    op.create_index(op.f('ix_stock_items_company_id'), 'stock_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_items_name'), 'stock_items', ['name'], unique=False)
    op.create_index(op.f('ix_stock_items_sku'), 'stock_items', ['sku'], unique=False)
    op.create_index(op.f('ix_stock_items_stock_group_id'), 'stock_items', ['stock_group_id'], unique=False)
    op.create_index(op.f('ix_stock_items_unit_id'), 'stock_items', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_items_unit_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_stock_group_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_sku'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_name'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_company_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_stock_groups_name'), table_name='stock_groups')
    op.drop_index(op.f('ix_stock_groups_company_id'), table_name='stock_groups')
    op.drop_table('stock_groups')
    # ### end Alembic commands ###
