"""add_stock_transfer_models

Revision ID: 856951d24c7b
Revises: b83eabde7d7f
Create Date: 2026-06-22 00:06:45.353984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '856951d24c7b'
down_revision: Union[str, Sequence[str], None] = 'b83eabde7d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('transfer_no', sa.String(length=100), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'POSTED', 'CANCELLED', name='invoicestatus', create_type=False), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_transfers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_stock_transfers_financial_year_id_financial_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_from_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_to_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_stock_transfers_voucher_id_vouchers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers')),
    sa.UniqueConstraint('company_id', 'financial_year_id', 'transfer_no', name='uq_stock_transfer_no'),
    sa.UniqueConstraint('voucher_id', name=op.f('uq_stock_transfers_voucher_id'))
    )
    op.create_index(op.f('ix_stock_transfers_company_id'), 'stock_transfers', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_financial_year_id'), 'stock_transfers', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_from_warehouse_id'), 'stock_transfers', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_warehouse_id'), 'stock_transfers', ['to_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_no'), 'stock_transfers', ['transfer_no'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('rate_snapshot', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_transfer_items_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('fk_stock_transfer_items_transfer_id_stock_transfers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfer_items'))
    )
    op.create_index(op.f('ix_stock_transfer_items_stock_item_id'), 'stock_transfer_items', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_stock_item_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfers_transfer_no'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_to_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_financial_year_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_company_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
