"""add_party_model

Revision ID: 856fcf11cfb1
Revises: 7057ba6e0177
Create Date: 2026-06-20 20:51:40.092571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856fcf11cfb1'
down_revision: Union[str, Sequence[str], None] = '7057ba6e0177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_parties_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_parties_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties')),
    sa.UniqueConstraint('company_id', 'name', name='uq_party_name_per_company'),
    sa.UniqueConstraint('ledger_id', name=op.f('uq_parties_ledger_id'))
    )
    op.create_index(op.f('ix_parties_company_id'), 'parties', ['company_id'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_company_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
