"""add_search_document_model

Revision ID: 9addf21aed7a
Revises: db35a676f3c6
Create Date: 2026-06-22 02:06:51.169954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9addf21aed7a'
down_revision: Union[str, Sequence[str], None] = 'db35a676f3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_search_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_documents'))
    )
    op.create_index(op.f('ix_search_documents_company_id'), 'search_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_search_documents_entity_id'), 'search_documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_search_documents_entity_type'), 'search_documents', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_documents_entity_type'), table_name='search_documents')
    op.drop_index(op.f('ix_search_documents_entity_id'), table_name='search_documents')
    op.drop_index(op.f('ix_search_documents_company_id'), table_name='search_documents')
    op.drop_table('search_documents')
    # ### end Alembic commands ###
