"""add_stock_adjustment_models

Revision ID: b83eabde7d7f
Revises: cbe8afc3d0fc
Create Date: 2026-06-21 23:51:16.249737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b83eabde7d7f'
down_revision: Union[str, Sequence[str], None] = 'cbe8afc3d0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_no', sa.String(length=100), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'POSTED', 'CANCELLED', name='invoicestatus', create_type=False), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_adjustments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_stock_adjustments_financial_year_id_financial_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_stock_adjustments_voucher_id_vouchers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_adjustments_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_adjustments')),
    sa.UniqueConstraint('company_id', 'financial_year_id', 'adjustment_no', name='uq_stock_adjustment_no'),
    sa.UniqueConstraint('voucher_id', name=op.f('uq_stock_adjustments_voucher_id'))
    )
    op.create_index(op.f('ix_stock_adjustments_adjustment_no'), 'stock_adjustments', ['adjustment_no'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_company_id'), 'stock_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_financial_year_id'), 'stock_adjustments', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_warehouse_id'), 'stock_adjustments', ['warehouse_id'], unique=False)
    op.create_table('stock_adjustment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('physical_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('difference_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('rate_snapshot', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['stock_adjustments.id'], name=op.f('fk_stock_adjustment_items_adjustment_id_stock_adjustments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_stock_adjustment_items_stock_item_id_stock_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_adjustment_items'))
    )
    op.create_index(op.f('ix_stock_adjustment_items_adjustment_id'), 'stock_adjustment_items', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustment_items_stock_item_id'), 'stock_adjustment_items', ['stock_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_adjustment_items_stock_item_id'), table_name='stock_adjustment_items')
    op.drop_index(op.f('ix_stock_adjustment_items_adjustment_id'), table_name='stock_adjustment_items')
    op.drop_table('stock_adjustment_items')
    op.drop_index(op.f('ix_stock_adjustments_warehouse_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_financial_year_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_company_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_adjustment_no'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
