"""add_initial_masters_models

Revision ID: c844bccb6d2e
Revises: 182bd93750f1
Create Date: 2026-06-20 20:36:16.885437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c844bccb6d2e'
down_revision: Union[str, Sequence[str], None] = '182bd93750f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('nature', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_account_groups_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['account_groups.id'], name=op.f('fk_account_groups_parent_id_account_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_groups'))
    )
    op.create_index(op.f('ix_account_groups_company_id'), 'account_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_account_groups_name'), 'account_groups', ['name'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_units_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_company_id'), 'units', ['company_id'], unique=False)
    op.create_table('ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ledgers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], name=op.f('fk_ledgers_group_id_account_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledgers'))
    )
    op.create_index(op.f('ix_ledgers_company_id'), 'ledgers', ['company_id'], unique=False)
    op.create_index(op.f('ix_ledgers_group_id'), 'ledgers', ['group_id'], unique=False)
    op.create_index(op.f('ix_ledgers_name'), 'ledgers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledgers_name'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_group_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_company_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_units_company_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_account_groups_name'), table_name='account_groups')
    op.drop_index(op.f('ix_account_groups_company_id'), table_name='account_groups')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
