"""add_audit_to_voucher_submodels

Revision ID: caa24718bf55
Revises: 307fd2c32f88
Create Date: 2026-06-20 21:07:45.041637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa24718bf55'
down_revision: Union[str, Sequence[str], None] = '307fd2c32f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inventory_transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inventory_transactions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('voucher_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('voucher_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('voucher_entries', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('voucher_entries', sa.Column('updated_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_entries', 'updated_by')
    op.drop_column('voucher_entries', 'created_by')
    op.drop_column('voucher_entries', 'updated_at')
    op.drop_column('voucher_entries', 'created_at')
    op.drop_column('inventory_transactions', 'updated_by')
    op.drop_column('inventory_transactions', 'created_by')
    op.drop_column('inventory_transactions', 'updated_at')
    op.drop_column('inventory_transactions', 'created_at')
    # ### end Alembic commands ###
