"""add_warehouse_to_invoice_items

Revision ID: cbe8afc3d0fc
Revises: 38084e22fae1
Create Date: 2026-06-21 23:45:07.783426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe8afc3d0fc'
down_revision: Union[str, Sequence[str], None] = '38084e22fae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('warehouse_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoice_items_warehouse_id'), 'invoice_items', ['warehouse_id'], unique=False)
    op.create_foreign_key(op.f('fk_invoice_items_warehouse_id_warehouses'), 'invoice_items', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoice_items_warehouse_id_warehouses'), 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_warehouse_id'), table_name='invoice_items')
    op.drop_column('invoice_items', 'warehouse_id')
    # ### end Alembic commands ###
