"""refine_masters_models

Revision ID: fe30ead5ce1d
Revises: c844bccb6d2e
Create Date: 2026-06-20 20:42:54.953941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe30ead5ce1d'
down_revision: Union[str, Sequence[str], None] = 'c844bccb6d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types manually
    sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', name='accountnature').create(op.get_bind())
    sa.Enum('DEBIT', 'CREDIT', name='balancetype').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_groups', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('account_groups', sa.Column('is_system', sa.Boolean(), nullable=False))
    # Drop and recreate nature column to handle Enum conversion cleanly on empty table
    op.drop_column('account_groups', 'nature')
    op.add_column('account_groups', sa.Column('nature', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', name='accountnature'), nullable=True))

    op.create_index(op.f('ix_account_groups_code'), 'account_groups', ['code'], unique=False)
    op.add_column('ledgers', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('ledgers', sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('ledgers', sa.Column('opening_balance_type', sa.Enum('DEBIT', 'CREDIT', name='balancetype'), nullable=False))
    op.add_column('ledgers', sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('ledgers', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('ledgers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_ledgers_code'), 'ledgers', ['code'], unique=False)
    op.add_column('units', sa.Column('is_system', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'is_system')
    op.drop_index(op.f('ix_ledgers_code'), table_name='ledgers')
    op.drop_column('ledgers', 'is_active')
    op.drop_column('ledgers', 'is_system')
    op.drop_column('ledgers', 'current_balance')
    op.drop_column('ledgers', 'opening_balance_type')
    op.drop_column('ledgers', 'opening_balance')
    op.drop_column('ledgers', 'code')
    op.drop_index(op.f('ix_account_groups_code'), table_name='account_groups')
    op.alter_column('account_groups', 'nature',
               existing_type=sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', name='accountnature'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('account_groups', 'is_system')
    op.drop_column('account_groups', 'code')
    # ### end Alembic commands ###
